version: 0.2

env:
  variables:
    REPOSITORY_URI: 234338175061.dkr.ecr.ap-northeast-1.amazonaws.com/yukimizuno-ecr2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing dependencies...
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 234338175061.dkr.ecr.ap-northeast-1.amazonaws.com)

  pre_build:
    commands:
      - echo Build started on `date`
      - printenv > .env
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - cp ./container/Dockerfile ./Dockerfile
      - cp ./codeBuild/appspec.yaml ./appspec.yaml
      - cp ./codeBuild/taskdef.json ./taskdef.json

  build:
    commands:
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"yukimizuno-ecr2","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - cat imageDetail.json

artifacts:
  files:
    - imagedefinitions.json
    - imageDetail.json
    - appspec.yaml
    - taskdef.json